version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-aws-athena-demo"
s3_bucket = "lambda-aws-athena-demo"
s3_prefix = "lambda-aws-athena-demo"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
