AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-aws-athena-demo

  Sample aws athena demonstration in SAM
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Resources:
  Function:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: index.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          DATABASE_NAME: TODO_DATABASE_NAME # Ex: database
          TABLE_NAME: TODO_DATABASE_NAME # Ex: table
          OUTPUT_LOCATION: TODO_OUTPUT_LOCATION # Ex s3://bucket-name/
          S3_URL_FOR_QUERY: TODO_S3_URL_FOR_QUERY # Ex: s3://bucket-name/your.json
          QUERY_DATE: TODO_QUERY_DATE # Ex: 2023-08-08
      Architectures:
        - x86_64
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - index.ts